import json
import joblib
from pathlib import Path
from typing import Any, Dict, List, Optional
import numpy as np
import pandas as pd


class DynamicServerManager:
    """Manages model serving, schema inference, and prediction execution."""

    @staticmethod
    def inspect_model_and_preprocessor(project_dir: Path) -> Dict[str, Any]:
        """Loads metadata, preprocessor and model to determine input schema."""
        model_path = project_dir / "model.joblib"
        prep_path = project_dir / "preprocessor.joblib"
        raw_csv_path = project_dir / "raw_data.csv"
        clean_csv_path = project_dir / "cleaned_data.csv"
        meta_path = project_dir / "metadata.json"

        metadata = {}
        if meta_path.exists():
            with open(meta_path, "r", encoding="utf-8") as f:
                metadata = json.load(f)

        target_col = metadata.get("target_column")
        task_type = metadata.get("task_type", "classification")

        # Feature schema from raw data (excluding target)
        feature_schema = []
        if raw_csv_path.exists():
            df_raw = pd.read_csv(raw_csv_path)
            for col in df_raw.columns:
                if col == target_col:
                    continue
                dtype = str(df_raw[col].dtype)
                is_num = pd.api.types.is_numeric_dtype(df_raw[col])
                sample_val = df_raw[col].dropna().iloc[0] if len(df_raw[col].dropna()) > 0 else 0
                feature_schema.append({
                    "name": col,
                    "type": "float" if is_num else "str",
                    "sample": float(sample_val) if is_num else str(sample_val),
                    "is_numeric": bool(is_num),
                    "unique_values": df_raw[col].dropna().unique()[:10].tolist() if not is_num else [],
                })

        return {
            "has_model": model_path.exists(),
            "has_preprocessor": prep_path.exists(),
            "target_column": target_col,
            "task_type": task_type,
            "feature_schema": feature_schema,
            "best_model": metadata.get("best_model"),
        }

    @staticmethod
    def predict(project_dir: Path, input_data: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Executes prediction on input_data using preprocessor and model."""
        model_path = project_dir / "model.joblib"
        prep_path = project_dir / "preprocessor.joblib"

        if not model_path.exists():
            raise FileNotFoundError("Model artifact model.joblib not found.")

        model = joblib.load(model_path)
        input_df = pd.DataFrame(input_data)

        # Apply preprocessor if it exists
        if prep_path.exists():
            try:
                preprocessor = joblib.load(prep_path)
                transformed = preprocessor.transform(input_df)
            except Exception:
                # If preprocessor expects raw schema or is partial
                transformed = input_df
        else:
            transformed = input_df

        predictions = model.predict(transformed)
        probabilities = None

        if hasattr(model, "predict_proba"):
            try:
                probs = model.predict_proba(transformed)
                probabilities = probs.tolist()
            except Exception:
                pass

        # Format output
        formatted_predictions = []
        for i, pred in enumerate(predictions):
            item = {"prediction": int(pred) if isinstance(pred, (np.integer, bool)) else (float(pred) if isinstance(pred, np.floating) else str(pred))}
            if probabilities and i < len(probabilities):
                item["probabilities"] = [round(float(p), 4) for p in probabilities[i]]
            formatted_predictions.append(item)

        return {
            "predictions": formatted_predictions,
            "count": len(formatted_predictions),
        }

    @staticmethod
    def generate_serve_script(
        project_dir: Path,
        target_col: str,
        task_type: str,
        feature_schema: List[Dict[str, Any]],
        best_model_name: str,
    ) -> str:
        """Generates self-contained standalone serve.py script for the project."""
        schema_fields = []
        for feat in feature_schema:
            py_type = "float" if feat["is_numeric"] else "str"
            sample = feat["sample"]
            if py_type == "str":
                schema_fields.append(f'    {feat["name"]}: {py_type} = "{sample}"')
            else:
                schema_fields.append(f'    {feat["name"]}: {py_type} = {sample}')

        fields_code = "\n".join(schema_fields) if schema_fields else "    # No features detected"

        script = f'''"""
Standalone FastAPI Model Serving Service
Auto-generated by EpochGo (Epochlypse Research)
Model: {best_model_name}
Target: {target_col} ({task_type})
"""

import os
from pathlib import Path
from typing import List, Optional
import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import uvicorn

app = FastAPI(
    title="EpochGo Model Serving API",
    description="Inference API for {best_model_name} trained on {target_col}",
    version="1.0.0",
)

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "model.joblib"
PREPROCESSOR_PATH = BASE_DIR / "preprocessor.joblib"

# Load artifacts
if not MODEL_PATH.exists():
    raise RuntimeError(f"Model file not found at {{MODEL_PATH}}")

model = joblib.load(MODEL_PATH)
preprocessor = joblib.load(PREPROCESSOR_PATH) if PREPROCESSOR_PATH.exists() else None


class FeatureInput(BaseModel):
{fields_code}


class PredictionOutput(BaseModel):
    prediction: Any = None
    probability: Optional[List[float]] = None


@app.get("/health")
def health_check():
    return {{
        "status": "healthy",
        "model": "{best_model_name}",
        "task_type": "{task_type}",
        "has_preprocessor": preprocessor is not None,
    }}


@app.post("/predict")
def predict_single(data: FeatureInput):
    try:
        df = pd.DataFrame([data.dict()])
        X = preprocessor.transform(df) if preprocessor else df
        pred = model.predict(X)[0]

        probs = None
        if hasattr(model, "predict_proba"):
            try:
                probs = model.predict_proba(X)[0].tolist()
            except Exception:
                pass

        val = int(pred) if hasattr(pred, "item") and isinstance(pred.item(), (int, bool)) else (
            float(pred) if hasattr(pred, "item") and isinstance(pred.item(), float) else str(pred)
        )
        return {{"prediction": val, "probability": probs}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/predict_batch")
def predict_batch(data: List[FeatureInput]):
    try:
        records = [d.dict() for d in data]
        df = pd.DataFrame(records)
        X = preprocessor.transform(df) if preprocessor else df
        preds = model.predict(X)

        probs = None
        if hasattr(model, "predict_proba"):
            try:
                probs = model.predict_proba(X).tolist()
            except Exception:
                pass

        results = []
        for i, p in enumerate(preds):
            res = {{"prediction": p.item() if hasattr(p, "item") else p}}
            if probs:
                res["probability"] = probs[i]
            results.append(res)
        return {{"predictions": results, "count": len(results)}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    port = int(os.getenv("PORT", "8001"))
    print(f"🚀 Starting model server on http://localhost:{{port}}")
    uvicorn.run(app, host="0.0.0.0", port=port)
'''
        return script
